base_url = "https://blog.keyrow.dev"
title = "keyrow's blog"
description = ""

compile_sass = true
build_search_index = true
generate_feeds = true
generate_sitemap = true

author = "keyrow"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
